pipeline:
    build:
       image: 10.1.86.51/devops/golang:1.7-godep
       commands:
         - echo "LABEL commit=$$COMMIT branch=$$BRANCH build_number=$$BUILD_NUMBER" >> Dockerfile
         - mkdir -p $GOPATH/src/github.com/fanux/pbrain && cp -r ./* $GOPATH/src/github.com/fanux/pbrain
         - cd $GOPATH/src/github.com/fanux/pbrain && godep go build -o pbrain
         - cd - && cp $GOPATH/src/github.com/fanux/pbrain .

    publish:
      image: plugins/docker
      username: admin
      password: Harbor12345
      registry: 10.1.86.51
      email: fhtjob@hotmail.com
      repo: 10.1.86.51/devops/pbrain
      tag: beta-v1.0
      # tag: ${DRONE_TAG}
      file: Dockerfile
      insecure: true
