version: '2'
services:
    pipeline:
      container_name: plugin-pipeline
      command: pbrain -H localhost -p :8081 pipeline
      network_mode: "host"
      image: 192.168.86.106:5000/pbrain:latest

    decider:
      container_name: plugin-decider
      command: pbrain -H localhost -p :8081 decider
      network_mode: "host"
      image: 192.168.86.106:5000/pbrain:latest
