version: '2'
services:
    pipeline:
      container_name: plugin-pipeline
      command: pbrain pipeline
      network_mode: "host"
      image: 192.168.86.106:5000/pbrain:latest

    decider:
      container_name: plugin-decider
      command: pbrain decider
      network_mode: "host"
      image: 192.168.86.106:5000/pbrain:latest
